# Generated by Selenium IDE
import os
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSuperadmin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_superadmin(self):
    wait = WebDriverWait(self.driver, 20)

    # 1. Authenticate session as Super Admin
    email = os.getenv("SYNAPSE_SUPER_ADMIN_EMAIL", "synapseadmin2255@gmail.com")
    password = os.getenv("SYNAPSE_SUPER_ADMIN_PASSWORD", "admin@synapse")

    self.driver.get("http://localhost:3000/login")
    self.driver.set_window_size(1084, 816)

    email_input = wait.until(EC.visibility_of_element_located((By.NAME, "email")))
    email_input.clear()
    email_input.send_keys(email)

    password_input = wait.until(EC.visibility_of_element_located((By.NAME, "password")))
    password_input.clear()
    password_input.send_keys(password)

    submit_button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button[type='submit']")))
    submit_button.click()

    # Wait for super admin redirect to /admin
    wait.until(lambda d: "/admin" in d.current_url)

    # 2. Click "Manage Companies" link
    manage_btn = wait.until(
        EC.element_to_be_clickable((By.XPATH, "//a[contains(., 'Manage Companies')]"))
    )
    manage_btn.click()

    # 3. Wait for companies list and click "Detail" on a company
    detail_links = wait.until(
        EC.presence_of_all_elements_located((By.XPATH, "//a[contains(., 'Detail')]"))
    )
    target_link = detail_links[1] if len(detail_links) > 1 else detail_links[0]
    wait.until(EC.element_to_be_clickable(target_link)).click()

    # 4. Open "Configure Custom Allocation" modal
    alloc_btn = wait.until(
        EC.element_to_be_clickable((By.XPATH, "//button[contains(., 'Configure Custom Allocation')]"))
    )
    alloc_btn.click()

    # 5. Toggle a capability if available and click "Review & Save"
    feature_btns = wait.until(
        EC.presence_of_all_elements_located((By.XPATH, "//button[contains(@class, 'rounded-xl') and .//span]"))
    )
    if feature_btns:
      try:
        feature_btns[0].click()
      except Exception:
        pass

    review_save_btn = wait.until(
        EC.element_to_be_clickable((By.XPATH, "//button[contains(., 'Review & Save')]"))
    )
    review_save_btn.click()

    # 6. Confirm in confirmation modal
    confirm_btn = wait.until(
        EC.element_to_be_clickable((By.XPATH, "//button[contains(., 'Confirm & Save')]"))
    )
    confirm_btn.click()

    # 7. Assert success message appears
    success_banner = wait.until(
        EC.visibility_of_element_located((By.XPATH, "//*[contains(text(), 'saved successfully') or contains(text(), 'Allocation Overrides')]"))
    )
    assert success_banner is not None, "Super admin custom allocation save failed."

  
