# Generated by Selenium IDE / Synapse AI Test Suite
import os
import time
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.chrome.options import Options


class TestAITestCaseGenerator:
    def setup_method(self, method):
        options = Options()
        if os.getenv("SELENIUM_HEADLESS", "false").lower() == "true":
            options.add_argument("--headless=new")
        options.add_argument("--no-sandbox")
        options.add_argument("--disable-dev-shm-usage")
        options.add_argument("--window-size=1280,900")
        self.driver = webdriver.Chrome(options=options)
        self.driver.implicitly_wait(10)

    def teardown_method(self, method):
        self.driver.quit()

    def test_ai_test_case_generator_workflow(self):
        wait = WebDriverWait(self.driver, 30)

        base_url = os.getenv("SYNAPSE_FRONTEND_URL", "http://localhost:3000")
        email = os.getenv("SYNAPSE_TEST_EMAIL", "arya@gmail.com")
        password = os.getenv("SYNAPSE_TEST_PASSWORD", "admin@synapse")
        project_id = "ff7c34f3-5621-4564-8674-b4462b637898"

        # -------------------------------------------------------------
        # 1. Login
        # -------------------------------------------------------------
        self.driver.get(f"{base_url}/login")

        email_input = wait.until(EC.visibility_of_element_located((By.NAME, "email")))
        email_input.clear()
        email_input.send_keys(email)

        password_input = wait.until(EC.visibility_of_element_located((By.NAME, "password")))
        password_input.clear()
        password_input.send_keys(password)

        submit_btn = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button[type='submit']")))
        submit_btn.click()

        wait.until(EC.url_changes(f"{base_url}/login"))

        # -------------------------------------------------------------
        # 2. Navigate to project requirements
        # -------------------------------------------------------------
        self.driver.get(f"{base_url}/projects/{project_id}/requirements")

        # -------------------------------------------------------------
        # 3. Open requirement
        # -------------------------------------------------------------
        wait.until(EC.visibility_of_element_located((By.XPATH, "//table//tbody//tr")))
        details_buttons = wait.until(
            EC.presence_of_all_elements_located((By.XPATH, "//button[contains(., 'Details')]"))
        )
        assert len(details_buttons) > 0, "No requirements found in the table."
        details_buttons[0].click()

        # -------------------------------------------------------------
        # 4. Open AI Test Cases tab
        # -------------------------------------------------------------
        tab_ai_test_cases = wait.until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, "[data-testid='tab-ai-test-cases']"))
        )
        tab_ai_test_cases.click()

        # -------------------------------------------------------------
        # 5. Click Generate Test Cases
        # -------------------------------------------------------------
        generate_btn = wait.until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, "[data-testid='generate-test-cases-btn']"))
        )
        generate_btn.click()

        # -------------------------------------------------------------
        # 6. Wait for actual generation (Ollama local inference)
        # -------------------------------------------------------------
        time.sleep(1.0)
        generation_wait = WebDriverWait(self.driver, 240)
        def _generation_done(d):
            try:
                btn = d.find_element(By.CSS_SELECTOR, "[data-testid='generate-test-cases-btn']")
                is_disabled = btn.get_attribute("disabled")
                return not is_disabled and "Generating" not in btn.text
            except Exception:
                return False

        generation_wait.until(_generation_done)

        # -------------------------------------------------------------
        # 7. Verify generated cases
        # -------------------------------------------------------------
        total_counter = wait.until(
            EC.visibility_of_element_located((By.CSS_SELECTOR, "[data-testid='count-total']"))
        )
        total_count = int(total_counter.text.strip())
        assert total_count > 0, f"Expected total test cases > 0, but got {total_count}"

        test_case_cards = wait.until(
            EC.presence_of_all_elements_located((By.XPATH, "//div[@data-testid='test-cases-list']/div"))
        )
        assert len(test_case_cards) > 0, "Expected test case cards to be rendered."

        # -------------------------------------------------------------
        # 8. Open Functional tab
        # -------------------------------------------------------------
        tab_func = wait.until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, "[data-testid='tab-category-functional']"))
        )
        tab_func.click()
        time.sleep(0.4)

        # -------------------------------------------------------------
        # 9. Open Negative tab
        # -------------------------------------------------------------
        tab_neg = wait.until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, "[data-testid='tab-category-negative']"))
        )
        tab_neg.click()
        time.sleep(0.4)

        # -------------------------------------------------------------
        # 10. Open Boundary tab
        # -------------------------------------------------------------
        tab_bound = wait.until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, "[data-testid='tab-category-boundary']"))
        )
        tab_bound.click()
        time.sleep(0.4)

        # -------------------------------------------------------------
        # 11. Open Acceptance tab
        # -------------------------------------------------------------
        tab_acc = wait.until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, "[data-testid='tab-category-acceptance']"))
        )
        tab_acc.click()
        time.sleep(0.4)

        # Return to All tab for editing and approval
        tab_all = wait.until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, "[data-testid='tab-category-all']"))
        )
        tab_all.click()
        time.sleep(0.4)

        # -------------------------------------------------------------
        # 12. Edit a test case
        # -------------------------------------------------------------
        edit_buttons = wait.until(
            EC.presence_of_all_elements_located((By.CSS_SELECTOR, "[data-testid^='edit-btn-']"))
        )
        edit_buttons[0].click()

        # Side drawer should open
        drawer_title_input = wait.until(
            EC.visibility_of_element_located((By.CSS_SELECTOR, "[data-testid='drawer-input-title']"))
        )
        original_title = drawer_title_input.get_attribute("value")
        edited_title = f"{original_title} (Verified E2E)"
        drawer_title_input.clear()
        drawer_title_input.send_keys(edited_title)

        # -------------------------------------------------------------
        # 13. Save
        # -------------------------------------------------------------
        save_btn = wait.until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, "[data-testid='drawer-save-btn']"))
        )
        save_btn.click()

        # Wait until drawer closes
        wait.until(
            EC.invisibility_of_element_located((By.CSS_SELECTOR, "[data-testid='drawer-input-title']"))
        )

        # -------------------------------------------------------------
        # 14. Approve test case
        # -------------------------------------------------------------
        approve_buttons = wait.until(
            EC.presence_of_all_elements_located((By.CSS_SELECTOR, "[data-testid^='approve-btn-']"))
        )
        assert len(approve_buttons) > 0, "No approve buttons found."
        approve_buttons[0].click()

        # -------------------------------------------------------------
        # 15. Verify APPROVED status
        # -------------------------------------------------------------
        wait.until(
            lambda d: int(d.find_element(By.CSS_SELECTOR, "[data-testid='count-approved']").text.strip()) > 0
        )
        approved_badge = wait.until(
            EC.visibility_of_element_located(
                (By.XPATH, "//span[contains(@data-testid, 'test-case-status-') and contains(text(), 'APPROVED')]")
            )
        )
        assert approved_badge is not None, "APPROVED status badge not found on test case card."

        # -------------------------------------------------------------
        # 16. Reload page
        # -------------------------------------------------------------
        self.driver.refresh()

        # -------------------------------------------------------------
        # 17. Verify persistence
        # -------------------------------------------------------------
        wait.until(EC.visibility_of_element_located((By.XPATH, "//table//tbody//tr")))
        reloaded_details_btns = wait.until(
            EC.presence_of_all_elements_located((By.XPATH, "//button[contains(., 'Details')]"))
        )
        reloaded_details_btns[0].click()

        reloaded_test_tab = wait.until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, "[data-testid='tab-ai-test-cases']"))
        )
        reloaded_test_tab.click()

        # Verify APPROVED badge still persists
        persisted_approved_badge = wait.until(
            EC.visibility_of_element_located(
                (By.XPATH, "//span[contains(@data-testid, 'test-case-status-') and contains(text(), 'APPROVED')]")
            )
        )
        assert persisted_approved_badge is not None, "Approved test case did not persist after page reload."
