# Generated by Selenium IDE
import os
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMeetingModule():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_meetingModule(self):
    wait = WebDriverWait(self.driver, 20)

    # 1. Authenticate session via login page
    email = os.getenv("SYNAPSE_TEST_EMAIL", "arya@gmail.com")
    password = os.getenv("SYNAPSE_TEST_PASSWORD", "admin@synapse")

    self.driver.get("http://localhost:3000/login")
    self.driver.set_window_size(1081, 816)

    email_input = wait.until(EC.visibility_of_element_located((By.NAME, "email")))
    email_input.clear()
    email_input.send_keys(email)

    password_input = wait.until(EC.visibility_of_element_located((By.NAME, "password")))
    password_input.clear()
    password_input.send_keys(password)

    submit_button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button[type='submit']")))
    submit_button.click()

    # Wait for login redirect
    wait.until(EC.url_changes("http://localhost:3000/login"))

    # 2. Navigate to meeting detail page
    self.driver.get("http://localhost:3000/projects/ff7c34f3-5621-4564-8674-b4462b637898/meetings/65264fb1-e1f2-409d-bd2e-bfcc80a423c8")

    # 3. Click the "Intelligence" tab
    intel_tab = wait.until(
        EC.element_to_be_clickable((By.XPATH, "//button[contains(., 'Intelligence')]"))
    )
    intel_tab.click()

    # 4. Advance through intelligence workflow to Action Items
    continue_btn = wait.until(
        EC.element_to_be_clickable((By.XPATH, "//button[contains(., 'Continue to Action Items')] | //button[contains(., 'Proceed to Review Intelligence')]"))
    )
    continue_btn.click()

    # 5. Open Add Action Item modal and dismiss it
    add_action_btn = wait.until(
        EC.element_to_be_clickable((By.XPATH, "//button[contains(., 'Add Action Item')]"))
    )
    add_action_btn.click()

    cancel_btn = wait.until(
        EC.element_to_be_clickable((By.XPATH, "//div[contains(@class, 'fixed')]//button[contains(text(), 'Cancel')]"))
    )
    cancel_btn.click()

    # 6. Interact with workflow step nodes in the tracker
    step_nodes = wait.until(
        EC.presence_of_all_elements_located((By.XPATH, "//div[contains(@class, 'cursor-pointer') and contains(@style, '120px')]"))
    )
    assert len(step_nodes) > 0, "Workflow tracker steps not found."
    for node in reversed(step_nodes):
      try:
        node.click()
        time.sleep(0.3)
      except Exception:
        pass

    # 7. Assert meeting details and intelligence workflow rendered properly
    assert "Order Lifecycle Architecture Review" in self.driver.page_source or "Intelligence" in self.driver.page_source

  
