# Generated by Selenium IDE
import os
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRequirementReviewChecker():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_requirementReviewChecker(self):
    wait = WebDriverWait(self.driver, 20)

    # 1. Authenticate session via login page
    email = os.getenv("SYNAPSE_TEST_EMAIL", "arya@gmail.com")
    password = os.getenv("SYNAPSE_TEST_PASSWORD", "admin@synapse")

    self.driver.get("http://localhost:3000/login")
    self.driver.set_window_size(1081, 816)

    email_input = wait.until(EC.visibility_of_element_located((By.NAME, "email")))
    email_input.clear()
    email_input.send_keys(email)

    password_input = wait.until(EC.visibility_of_element_located((By.NAME, "password")))
    password_input.clear()
    password_input.send_keys(password)

    submit_button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button[type='submit']")))
    submit_button.click()

    # Wait for login redirect
    wait.until(EC.url_changes("http://localhost:3000/login"))

    # 2. Navigate to requirements page
    self.driver.get("http://localhost:3000/projects/ff7c34f3-5621-4564-8674-b4462b637898/requirements")

    # 3. Wait for requirements table and click "Review with AI" on the 5th requirement
    review_buttons = wait.until(
        EC.presence_of_all_elements_located((By.XPATH, "//button[contains(., 'Review with AI')]"))
    )
    target_button = review_buttons[4] if len(review_buttons) >= 5 else review_buttons[-1]
    wait.until(EC.element_to_be_clickable(target_button)).click()

    # 4. Wait for AI Review modal to appear and findings to load
    wait.until(EC.visibility_of_element_located((By.XPATH, "//h2[contains(text(), 'AI Requirement Review')]")))

    # Wait for finding cards / evidence buttons to be rendered
    evidence_buttons = wait.until(
        EC.presence_of_all_elements_located((By.XPATH, "//button[contains(., 'Inspect Grounded Evidence')]"))
    )
    if evidence_buttons:
      evidence_buttons[0].click()

    # Click Accept on a finding
    accept_buttons = wait.until(
        EC.presence_of_all_elements_located((By.XPATH, "//button[contains(., 'Accept')]"))
    )
    if accept_buttons:
      accept_buttons[0].click()

    # 5. Close the review modal
    close_button = wait.until(
        EC.element_to_be_clickable((By.XPATH, "//div[contains(@class, 'border-b')]//button[contains(@class, 'p-2')]"))
    )
    close_button.click()

    # Assert modal has closed
    modal_closed = wait.until(
        EC.invisibility_of_element_located((By.XPATH, "//h2[contains(text(), 'AI Requirement Review')]"))
    )
    assert modal_closed, "Requirement Review modal did not close properly."

  
