# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginandlanding():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginandlanding(self):
    wait = WebDriverWait(self.driver, 15)

    self.driver.get("http://localhost:3000/login")
    self.driver.set_window_size(1075, 816)

    # Wait for email input and enter credentials
    email_input = wait.until(EC.visibility_of_element_located((By.NAME, "email")))
    email_input.clear()
    email_input.send_keys("synapseadmin2255@gmail.com")

    # Enter password
    password_input = wait.until(EC.visibility_of_element_located((By.NAME, "password")))
    password_input.clear()
    password_input.send_keys("admin@synapse")

    # Click the sign-in submit button
    submit_button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button[type='submit']")))
    submit_button.click()

    # Wait for navigation away from login and landing on dashboard
    wait.until(EC.url_changes("http://localhost:3000/login"))
    wait.until(lambda d: "/dashboard" in d.current_url or "/admin" in d.current_url)

    assert "/login" not in self.driver.current_url, f"Login failed or did not redirect. Current URL: {self.driver.current_url}"

  
