# Generated by Selenium IDE
import os
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestkbindex():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testkbindex(self):
    wait = WebDriverWait(self.driver, 20)

    # 1. Authenticate session via login page
    email = os.getenv("SYNAPSE_TEST_EMAIL", "arya@gmail.com")
    password = os.getenv("SYNAPSE_TEST_PASSWORD", "admin@synapse")

    self.driver.get("http://localhost:3000/login")
    self.driver.set_window_size(1080, 816)

    email_input = wait.until(EC.visibility_of_element_located((By.NAME, "email")))
    email_input.clear()
    email_input.send_keys(email)

    password_input = wait.until(EC.visibility_of_element_located((By.NAME, "password")))
    password_input.clear()
    password_input.send_keys(password)

    submit_button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button[type='submit']")))
    submit_button.click()

    # Wait for login redirect
    wait.until(EC.url_changes("http://localhost:3000/login"))

    # 2. Navigate to project knowledge page
    self.driver.get("http://localhost:3000/projects/ff7c34f3-5621-4564-8674-b4462b637898/knowledge")

    # 3. Find and click "Index Project Artifacts" button
    index_button = wait.until(
        EC.element_to_be_clickable((By.XPATH, "//button[contains(., 'Index Project Artifacts')]"))
    )
    index_button.click()

    # 4. Wait for indexing to complete and verify success notice
    success_notice = wait.until(
        EC.visibility_of_element_located((By.XPATH, "//*[contains(text(), 'Indexed') or contains(text(), 'chunks')]"))
    )
    assert success_notice is not None, "Indexing completion message was not displayed."


  
