"""phase1_foundation_refinements

Revision ID: 1d48bc523904
Revises: b10f8f27a746
Create Date: 2026-07-27 01:33:13.071405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d48bc523904'
down_revision: Union[str, Sequence[str], None] = 'b10f8f27a746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_jobs',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='aijobstatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_metadata', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_jobs_type'), 'ai_jobs', ['type'], unique=False)
    op.create_table('task_comments',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_comments_task_id'), 'task_comments', ['task_id'], unique=False)
    op.add_column('tasks', sa.Column('reporter_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('reviewer_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'users', ['reporter_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'reviewer_id')
    op.drop_column('tasks', 'reporter_id')
    op.drop_index(op.f('ix_task_comments_task_id'), table_name='task_comments')
    op.drop_table('task_comments')
    op.drop_index(op.f('ix_ai_jobs_type'), table_name='ai_jobs')
    op.drop_table('ai_jobs')
    # ### end Alembic commands ###
