"""refactor_user_permissions

Revision ID: 6a894979bb9e
Revises: 0d5eb73786f9
Create Date: 2026-07-22 08:36:40.060529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a894979bb9e'
down_revision: Union[str, Sequence[str], None] = '0d5eb73786f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # ALTER TYPE ADD VALUE cannot run inside transaction blocks in older PG versions, so we commit the transaction first.
        op.execute("COMMIT")
        op.execute("ALTER TYPE companyrole ADD VALUE IF NOT EXISTS 'MEMBER'")
        op.execute("ALTER TYPE companyrole ADD VALUE IF NOT EXISTS 'VIEWER'")
        
    op.add_column('users', sa.Column('designation', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'designation')
    # ### end Alembic commands ###
