"""add_pending_memberships_table

Revision ID: b10f8f27a746
Revises: e9586fe62148
Create Date: 2026-07-26 18:47:44.902158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM


# revision identifiers, used by Alembic.
revision: str = 'b10f8f27a746'
down_revision: Union[str, Sequence[str], None] = 'e9586fe62148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_memberships',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', PG_ENUM('PROJECT_MANAGER', 'TEAM_LEAD', 'BACKEND_DEVELOPER', 'FRONTEND_DEVELOPER', 'AI_ENGINEER', 'UI_UX_DESIGNER', 'QA_ENGINEER', 'DEVOPS_ENGINEER', 'VIEWER', name='projectrole', create_type=False), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_memberships_email'), 'pending_memberships', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_memberships_email'), table_name='pending_memberships')
    op.drop_table('pending_memberships')
    # ### end Alembic commands ###
