"""add_meeting_intelligence_tables

Revision ID: b210ab5931b0
Revises: d8e9f0a1b2c3
Create Date: 2026-08-14 23:21:22.378439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b210ab5931b0'
down_revision: Union[str, Sequence[str], None] = 'd8e9f0a1b2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql

    op.create_table('meeting_analyses',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('meeting_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ai_job_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('status', postgresql.ENUM('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='requirementreviewstatus', create_type=False), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('decisions', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('retrieved_chunk_ids', sa.JSON(), nullable=True),
    sa.Column('similarity_scores', sa.JSON(), nullable=True),
    sa.Column('retrieval_latency_ms', sa.Float(), nullable=False),
    sa.Column('generation_latency_ms', sa.Float(), nullable=False),
    sa.Column('total_latency_ms', sa.Float(), nullable=False),
    sa.Column('raw_output_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ai_job_id'], ['ai_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_analyses_ai_job_id'), 'meeting_analyses', ['ai_job_id'], unique=False)
    op.create_index(op.f('ix_meeting_analyses_company_id'), 'meeting_analyses', ['company_id'], unique=False)
    op.create_index(op.f('ix_meeting_analyses_meeting_id'), 'meeting_analyses', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_analyses_project_id'), 'meeting_analyses', ['project_id'], unique=False)
    op.create_index(op.f('ix_meeting_analyses_status'), 'meeting_analyses', ['status'], unique=False)
    op.create_table('meeting_task_suggestions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('analysis_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('meeting_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('workstream', postgresql.ENUM('UI_UX', 'FRONTEND', 'BACKEND', 'QA', 'DEVOPS', 'AI_ML', 'GENERAL', name='taskworkstream', create_type=False), nullable=False),
    sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority', create_type=False), nullable=False),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('requirement_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('human_decision', postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'MODIFIED', 'FALSE_POSITIVE', name='findinghumandecision', create_type=False), nullable=False),
    sa.Column('human_comment', sa.Text(), nullable=True),
    sa.Column('created_task_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['meeting_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_task_suggestions_analysis_id'), 'meeting_task_suggestions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_meeting_task_suggestions_company_id'), 'meeting_task_suggestions', ['company_id'], unique=False)
    op.create_index(op.f('ix_meeting_task_suggestions_human_decision'), 'meeting_task_suggestions', ['human_decision'], unique=False)
    op.create_index(op.f('ix_meeting_task_suggestions_meeting_id'), 'meeting_task_suggestions', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_task_suggestions_project_id'), 'meeting_task_suggestions', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_meeting_task_suggestions_project_id'), table_name='meeting_task_suggestions')
    op.drop_index(op.f('ix_meeting_task_suggestions_meeting_id'), table_name='meeting_task_suggestions')
    op.drop_index(op.f('ix_meeting_task_suggestions_human_decision'), table_name='meeting_task_suggestions')
    op.drop_index(op.f('ix_meeting_task_suggestions_company_id'), table_name='meeting_task_suggestions')
    op.drop_index(op.f('ix_meeting_task_suggestions_analysis_id'), table_name='meeting_task_suggestions')
    op.drop_table('meeting_task_suggestions')
    op.drop_index(op.f('ix_meeting_analyses_status'), table_name='meeting_analyses')
    op.drop_index(op.f('ix_meeting_analyses_project_id'), table_name='meeting_analyses')
    op.drop_index(op.f('ix_meeting_analyses_meeting_id'), table_name='meeting_analyses')
    op.drop_index(op.f('ix_meeting_analyses_company_id'), table_name='meeting_analyses')
    op.drop_index(op.f('ix_meeting_analyses_ai_job_id'), table_name='meeting_analyses')
    op.drop_table('meeting_analyses')
    # ### end Alembic commands ###
